### ISSUE TITLE
server side rendering is failing

### ISSUE THREAD

**Issue by Ajar-Ajar** [chenjiahan/rodal#4]
Universal apps rendering their initial render on the server cannot use this library since it has a document and window dependency. 
Please add to your script logic the following test to check if this is running in fact on the client...
```
var canUseDOM = !!(
  typeof window !== 'undefined' &&
  window.document &&
  window.document.createElement
);
```

**Comment by chenjiahan** [comment]
@Ajar-Ajar Thank you for your suggestion, This has been fixed in version 1.2.10,  please try again.

**Comment by ajliv** [comment]
Hey @chenjiahan, an upgrade to 1.2.10 still throws a "ReferenceError: window is not defined" for me during server-side render. 

React v15 added onAnimationEnd support, which would remove the need for the animationEvents.js util I believe the error is still originating from, I submitted #5 to use this if you wanna consider it. :)

**Comment by chenjiahan** [comment]
@ajliv Thank you for your pull request :+1:  This has been included in v1.3.0.
